name: test/build/push
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python env setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: test format
        run: make test-format
      - name: test lint
        run: make test-lint
      - name: test types
        run: make test-types
      - name: test licenses
        run: make test-license
